baseURL        = "https://jyotsnad246.github.io/jyotsnad246.github.io"
title          = "Hi, I'm Jyotsna"
languageCode   = "en-us"
theme          = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle      = "monokai"

# Directory structure
archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

# Build configuration
buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

# Enable and disable certain features
enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

# Pagination settings
[pagination]
  disableAliases = false
  pagerSize      = 20
  path           = "page"

# Services
[services]
  [services.rss]
      # Maximum number of items in the RSS feed.
      limit = 42

  # Uncomment and configure these services as needed:
  # [services.disqus]
  # shortname = "your-disqus-shortname"
  # [services.googleAnalytics]
  # ID = "G-MEASUREMENT_ID"

# Permalinks structure
[permalinks]
  posts = "/posts/:year/:month/:title/"

# Blackfriday Markdown settings
[blackfriday]
  hrefTargetBlank = true

# Taxonomies
[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

# Date formatting options
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Metadata used in the document's head
  description = "Nice theme for homepages and blogs"
  keywords    = ""
  images      = [""]

  # Home subtitle of the index page
  homeSubtitle = "Engineering next-gen resilient solutions that scale with innovation and performance"

  # Enable theme toggle for dark/light mode
  enableThemeToggle = true

  # Sharing buttons configuration
  enableSharingButtons = true

  # Global language menu
  enableGlobalLanguageMenu = false

  # Custom CSS and JS integration
  customCSS = []
  customJS  = []

  # Toggle SCSS rebuild (requires extended version of Hugo)
  justifyContent = false

  # Enable Plausible.io integration
  # plausibleDataDomain = 'yourdomain.com'
  # plausibleScriptSource = 'https://plausible.io/js/script.js'

  # Footer configuration
  [params.footer]
    topText = [
      "Made with &#10084; by <a href=\"https://github.com/jyotsnad246\">Jyotsna</a>"
    ]
    trademark = 2025
    rss = false
    copyright = false
    author = false

  # Favicon colors
  [params.favicon.color]
    mask          = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme         = "#1b1c1d"

  # Logo configuration
  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Uncomment below to adjust cursor behavior in the logo.
    # logoCursorDisabled = false
    # logoCursorColor    = "#67a2c9"
    # logoCursorAnimate  = "2s"
    # logoCursorPathname = true

  # Portrait configuration (Uncomment and set the correct path to your image)
  [params.portrait]
  path     = "/images/jyotsna.jpeg"   # Corrected path relative to static folder
  alt      = "Portrait of Jyotsna"    # Descriptive alt text
  maxWidth = "350px"                  # Adjusted max width for better display

  # Commento integration (Uncomment to enable)
  # [params.commento]
  # url = "your-commento-instance-url"

  # Utteranc.es integration (Uncomment to enable)
  # [params.utterances]
  # repository = "your-github-repository"
  # label      = "comments"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:emailofjyotsna@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/jyotsnad246"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/jyotsna246/"

  [[params.social]]
    name = "medium"
    url  = "https://medium.com/@jyotsnay24/"

  [[params.social]]
    name = "instagram"
    url  = "https://instagram.com/jyotsnadoonga"
  
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

  [[menu.main]]
    identifier = "blog"
    name       = "Blogs"
    url        = "posts/"
